# Generated by Django 2.2.1 on 2019-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(help_text='Enter an alert message (max 500 characters).', max_length=250),
        ),
    ]
