# Generated by Django 2.2.2 on 2019-06-24 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190616_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(help_text='Enter an alert message (max 500 characters). You may use HTML elements in this message.', max_length=500),
        ),
        migrations.AlterField(
            model_name='contactnotificant',
            name='email',
            field=models.EmailField(help_text='An email address of an officer wanting to receive contact requests.', max_length=254),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(help_text='The latitude in degrees (must be between -90 and 90). For help on finding the latitude and longitude, see [https://support.google.com/maps/answer/18539].', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(help_text='The longitude in degrees (must be between -180 and 180).For help on finding the latitude and longitude, see [https://support.google.com/maps/answer/18539].', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='videoofday',
            name='link',
            field=models.CharField(help_text="The link to the video of the day. Please enter the full link (e.g. 'https://www.google.com' instead of 'google.com').", max_length=1000),
        ),
    ]
