# Generated by Django 2.2.1 on 2019-05-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamebring_location_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('old_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('choice', models.CharField(choices=[('a', 'Add New'), ('m', 'Modify Existing'), ('d', 'Delete')], default='a', max_length=1)),
            ],
        ),
    ]
