# Generated by Django 2.2.2 on 2019-06-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190624_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameofweek',
            name='image',
        ),
        migrations.AddField(
            model_name='gameofweek',
            name='image_url',
            field=models.CharField(default='https://www.google.com', help_text="The link to the image of the game of the week. Please enter the full link (e.g. 'https://www.google.com' instead of 'google.com').", max_length=1000),
            preserve_default=False,
        ),
    ]
