# Generated by Django 2.2.1 on 2019-05-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_emailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='drifters',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
