# Generated by Django 2.2.1 on 2019-05-13 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gamescore_drifters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
