# Generated by Django 2.2.1 on 2019-05-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
