# Generated by Django 2.2.1 on 2019-05-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190516_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.MassEmail'),
        ),
    ]
