# Generated by Django 2.2.1 on 2019-05-21 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190520_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='massemail',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='massemail',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 21, 23, 45, 13, 366371, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
