# Generated by Django 2.2.1 on 2019-05-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190521_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('m', 'Message'), ('a', 'Alert'), ('w', 'Warning')], default='w', max_length=1),
            preserve_default=False,
        ),
    ]
