# Generated by Django 2.2.1 on 2019-05-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190522_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-severity', 'time']},
        ),
    ]
