# Generated by Django 2.2.1 on 2019-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190522_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('m', 'Message'), ('t', 'Alert'), ('w', 'Warning')], max_length=1),
        ),
    ]
