# Generated by Django 2.2.1 on 2019-05-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190522_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('1m', 'Message'), ('2a', 'Alert'), ('3w', 'Warning')], max_length=2),
        ),
    ]
