# Generated by Django 2.2.1 on 2019-05-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190522_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailRequest',
        ),
    ]
