# Generated by Django 2.2.1 on 2019-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190523_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebring',
            name='game',
            field=models.CharField(max_length=100),
        ),
    ]
