# Generated by Django 2.2.1 on 2019-05-24 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190523_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='videoofday',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoteofday',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
