# Generated by Django 2.2.1 on 2019-05-24 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190523_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['time']},
        ),
    ]
