# Generated by Django 2.2.1 on 2019-05-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190523_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoofday',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videoofday',
            name='visible_text',
            field=models.CharField(default='yes;', max_length=500),
            preserve_default=False,
        ),
    ]
