# Generated by Django 2.2.1 on 2019-05-30 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_gameofweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameofweek',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
