# Generated by Django 2.2.1 on 2019-06-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190531_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('1m', 'Message'), ('2a', 'Alert'), ('3w', 'Warning')], default='2a', help_text='Determines the severity of the alert (which changes the banner appearance).', max_length=2),
        ),
    ]
