# Generated by Django 2.2.1 on 2019-06-01 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190531_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time and date when the contact request was created.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address of the contact request sender (optional).', max_length=254, null=True, verbose_name='email address'),
        ),
    ]
