# Generated by Django 2.2.1 on 2019-06-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190531_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massemail',
            options={'ordering': ['last_edit'], 'permissions': (('can_send_emails', 'Abilty to send club emails'),)},
        ),
    ]
