# Generated by Django 2.2.1 on 2019-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20190531_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massemail',
            name='last_edit',
            field=models.DateTimeField(help_text='The time of the last edit of the mass email.'),
        ),
    ]
